update: add functions
trackier/cordova_sdk pull request #11
Opened 2023-08-31 15:29 UTC by IloveJavaa

Asana - https://app.asana.com/0/0/1205371519209335/f

2023-08-31 16:34 UTC, Hemant-Mann requested changes

2023-08-31 16:34 UTC, Hemant-Mann commented on src/android/TrackierCordovaPlugin.java
> +                String data = "sanu";// com.trackier.sdk.TrackierSDK.getTrackierId();
fix this

2023-08-31 16:34 UTC, Hemant-Mann commented on src/android/TrackierCordovaPlugin.java
> +                return true;
return true

should be moved out of the if else if @IloveJavaa

2023-08-31 16:58 UTC, IloveJavaa commented on src/android/TrackierCordovaPlugin.java
> +                String data = "sanu";// com.trackier.sdk.TrackierSDK.getTrackierId();
done

2023-08-31 16:58 UTC, IloveJavaa commented on src/android/TrackierCordovaPlugin.java
> +                return true;
done

2023-09-01 06:43 UTC, Hemant-Mann approved these changes

2023-09-01 06:43 UTC, merged