Update README.md
trackier/cordova_sdk pull request #8
Opened 2022-08-31 09:32 UTC by IloveJavaa

2022-08-31 12:36 UTC, Hemant-Mann requested changes

2022-08-31 12:36 UTC, Hemant-Mann commented on README.md
> +You can downloads the trackier by the click on below link.
```suggestion
You can download the trackier folder by the click on below link.
```

2022-08-31 12:36 UTC, Hemant-Mann commented on README.md
> +1.Login to your Trackier MMP account.
New lines not visible in the markdown @IloveJavaa

2022-08-31 12:36 UTC, Hemant-Mann commented on README.md
>  After follow all steps, Your SDK key look like the below screenshot
```suggestion
After following all the steps, Your SDK key should look like the below screenshot
```

2022-08-31 12:42 UTC, IloveJavaa commented on README.md
> +You can downloads the trackier by the click on below link.
Done

2022-09-01 06:03 UTC, Hemant-Mann approved these changes

2022-09-01 06:03 UTC, merged